### ISSUE TITLE
ShouldMoveToTabAtIndex

### ISSUE THREAD

**Issue by stelarelas** [Minitour/AZTabBarController#10]
Hey there!

Is there a way to either disable a tab bar button or add an action to prevent navigating to the viewController assigned to this button?

Perhaps a shouldMoveToTabAtIndex function would be useful.

**Comment by Minitour** [comment]
@stelarelas Ok I created the delegate function, I will be update the pod in few minutes.
This is how you use it:

```swift
func tabBar(_ tabBar: AZTabBarController, shouldMoveToTabAtIndex index: Int) -> Bool {
        return !(index == 3)
}
```

I also recommend you add this to disable the animation at the disabled index:
```swift
func tabBar(_ tabBar: AZTabBarController, shouldAnimateButtonInteractionAtIndex index: Int) -> Bool {
        return !(index == 3)
}
```

Please note that this will simply disable the transition from controller to controller. If you have actions set on that index they will be triggered when clicking the tab.

**Comment by stelarelas** [comment]
Working like a charm!

Thank you very much @Minitour! Your assistance is greatly appreciated!

**Comment by Minitour** [comment]
Happy to help 😊
