### ISSUE TITLE
Change tab bar icons on the fly

### ISSUE THREAD

**Issue by ispiropoulos** [Minitour/AZTabBarController#13]
Is there any way I could change one Icon on the fly without reinitializing the tab bar controller?

eg: tabController.setButtonImage(forIndex: Int, image: UIImage, highlightedImage: UIImage)

**Comment by Minitour** [comment]
@ispiropoulos There you go:
```swift
open func setButtonImage(forIndex index: Int, normal: UIImage,selected: UIImage){
        self.tabIcons?[index] = normal
        self.selectedTabIcons?[index] = selected
        updateInterfaceIfNeeded()
    }
```

Just put this function anywhere in the class and it should work.

**Comment by ispiropoulos** [comment]
Thank you, but this is what I get, probably due to the fact that the images are not monochrome but for example a profile picture. The last tab icon
<img width="322" alt="screen shot 2017-05-15 at 18 13 26" src="https://cloud.githubusercontent.com/assets/2028642/26064641/42abcee0-399a-11e7-97ff-ac7493f5e1d1.png">
 is the one that changed
