### ISSUE TITLE
Customize tabbar

### ISSUE THREAD

**Issue by longhoang2984** [Minitour/AZTabBarController#14]
Hi @Minitour , 

How can I customize your tabbar like that:

![tab bar navigation](https://cloud.githubusercontent.com/assets/11419002/26648221/f30fdeec-466b-11e7-8f89-ed8575a25d4a.png)

**Comment by Minitour** [comment]
@longhoang2984 Have a look at this issue:
https://github.com/Minitour/AZTabBarController/issues/11

**Comment by longhoang2984** [comment]
@Minitour 
thanks you very much <3
