### ISSUE TITLE
Tabbar color with opacity

### ISSUE THREAD

**Issue by freeubi** [Minitour/AZTabBarController#23]
Hello,

i just tried to make the tab bar color a little transparent, but it seems it doesn't handle the alpha values correctly.

**Comment by Minitour** [comment]
@freeubi The thing is that the tab bar is not meant to be opaque. You see, the content of the controllers (the tabs) is not set beneath the tab bar. Furthermore, when you set the tab bar to be transparent, what you'll see is going to be the background of the controller, which is white if I am not mistaken.

If you still want to get that transparent effect, you will need to modify the layout constraints of the views in the `loadView` function.
