### ISSUE TITLE
How do I get selectedViewController from AZTabBarController?

### ISSUE THREAD

**Issue by akhilcb** [Minitour/AZTabBarController#28]
Thanks for the great library. I am using this library through cocoapods and I have a query. I am trying to get `selectedViewController` from `AZTabBarController` similar to the same property in `UITabBarController`, but I am not able to locate it. Please let me know how I can get that. If possible please add the same to the library itself so that it would be useful to more people.

**Comment by Minitour** [comment]
@akhilcb Hi, at the moment there is no such property, I recommended that you keep an array that holds your controllers. However if you want a quick solution you can use this code:

Include this extension in the ```AZTabBarController.swift```:
```swift
public extension AZTabBarController {
    public var currentTab: UIViewController? {
        if selectedIndex >= 0,selectedIndex < tabCount, let controller = controllers[selectedIndex] { return controller }
        return nil
    }
}
```

You can then call it like so:
```swift
let controller: UIViewController? = tabBar.currentTab
```

**Comment by akhilcb** [comment]
Thanks. This what I ended up doing. It would be really helpful for others too if you could add this as a property of AZTabBarController itself in next release. Especially when someone is switching from UITabBarController to AZTabBarController, this will help.

**Comment by Minitour** [comment]
@akhilcb Alright, I will include this in the next release. Thank you for your feedback.
