### ISSUE TITLE
BadgeAppearnce typo? -> build errors

### ISSUE THREAD

**Issue by peterlbrooks** [Minitour/AZTabBarController#29]
/// The appearance of the notification badge.
    open var notificationBadgeAppearance: BadgeAppearnce = BadgeAppearnce()

**Comment by Minitour** [comment]
@peterlbrooks do `pod update`

**Comment by peterlbrooks** [comment]
To support swift 3 not 4 which max version should I add to the podfile (pod 'AZTabBarController', '< ?.??' if any?

**Comment by Minitour** [comment]
@peterlbrooks the latest version that supports swift 3.0 is 1.3.0.

**Comment by Minitour** [comment]
@peterlbrooks Here is your solution:
```
pod 'AZTabBar', '1.3.0'
pod 'EasyNotificationBadge', '1.1.1'
```

These are both compatible with Swift 3.2 and each other. let me know if you got it to work.

**Comment by peterlbrooks** [comment]
Seem to get 2 msgs - Could not infer type for 'notificationBadgeAppearance', and Use of undeclared type 'BadgeAppearnce' at 

 open var notificationBadgeAppearance: BadgeAppearnce = BadgeAppearnce()

pod update results are:

- Using AZSearchView (1.0.3)
- Using AZTabBar (1.3.0)
-Using EasyNotificationBadge (1.1.1)

and in my viewcontroller:

- import AZSearchView (not AZTabBar or EasyNotificationBadge)

**Comment by Minitour** [comment]
If the word `BadgeAppearance` is misspelled then you are not using `1.3.0`:

https://github.com/Minitour/AZTabBarController/blob/d9ad21d015306528b86112c4ffa44c5fd7858d0b/Sources/AZTabBarController.swift#L160

However I will look into it.

**Comment by Minitour** [comment]
Ok I just create a new project with this podfile:
```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FrameworkDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FrameworkDemo
  pod ‘AZTabBar’, ‘1.3.0’
  pod ‘EasyNotificationBadge’, ‘1.1.1’
end
```

And it compiled perfectly normal.

**Comment by peterlbrooks** [comment]
I will look into this later today then. Thanks for your quick support!

**Comment by Minitour** [comment]
No problem, be sure to update me when you figure it out.

**Comment by peterlbrooks** [comment]
Will re-try in a few days. I assume that it will be working per your comment, so will close this issue.
