### ISSUE TITLE
Calling setButtonTintColor(color: UIColor, atIndex: Int) in VC viewDidAppear() causes crash

### ISSUE THREAD

**Issue by BrettRosen** [Minitour/AZTabBarController#32]
Calling:

`tabController.setButtonTintColor(color: UIColor, atIndex: Int)` in the `viewDidAppear()` method of the VC in which you are using tabController causes a crash because `self.buttons` seems to be nil at the time.

**Comment by Minitour** [comment]
@BrettRosen I re-implemented the entire function. I tested some use-case examples and it seems pretty stable. Feel free to report any issues sorry for the delay 😅

The new pod release is `1.3.2`. Feel free to close the issue when you solve your problem.

Thanks for contributing 😁
