### ISSUE TITLE
Logo design proposal

### ISSUE THREAD

**Issue by Tobaloidee** [Minitour/AZTabBarController#35]
Good day Sir @Minitour  I am a graphics designer and i want to contribute to your project by designing a logo for it as i have noticed it doesn't have one yet. I will be gladly doing it as a gift for free if you will permit me. Thanks and best regards! - Tobaloidee

**Comment by Minitour** [comment]
@Tobaloidee I'd be more than happy to have you do the logo. 😄

**Comment by Tobaloidee** [comment]
Sorry for the late response Sir, I am going to start my design now..

**Comment by Tobaloidee** [comment]
Here's what i came up with Sir, 

- Letters A Z above the tab bar shape design

2 variation options

![az-01](https://user-images.githubusercontent.com/36028424/41611236-d878c726-7421-11e8-8a5a-ad8608ef6470.png)

please let me know if you what you have in mind or there's any modifications

**Comment by Minitour** [comment]
@Tobaloidee Looks interesting, however I'm getting a weird vibe from the tab bar in the icon. 
Can you send another version without the "highlight indicator" (the moving line) and instead add 5 or 3 different shapes (icons) spread across the bar equally.

**Comment by Tobaloidee** [comment]
Here Sir @Minitour , Goodmorning!

![az-03](https://user-images.githubusercontent.com/36028424/41630231-8aea5224-7460-11e8-829a-b0f2c9d5797e.png)

**Comment by Minitour** [comment]
@Tobaloidee Sorry for the late response, was a busy week.
I like the version with the green-white logo, I guess I can go with that.

**Comment by Tobaloidee** [comment]
Okay Sir..will make a PR and upload the new logo files and put it in readme also..thanks a lot!

**Comment by Tobaloidee** [comment]
Here's the PR #37 where i uploaded the logo files & updated the readme also, Thanks!
