### ISSUE TITLE
Pushed to new controller from its child controller

### ISSUE THREAD

**Issue by Sajjad-Zafar** [Minitour/AZTabBarController#36]
how to hide the tabbar on a view controller that is pushed from tab 0.

**Comment by Minitour** [comment]
@Sajjad-Zafar Hi, sorry for the late response. There are 2 ways of dealing with this issue:

1. Push from the tab bar controller and not from tab 0:
```swift
//in tab 0
self.currentTabBar?.pushViewController(controller, animated: true)
```

2. Push from tab 0 but hide the bar
```swift
self.currentTabBar?.set(hidden: true)
pushViewController(controller, animated: true)
```

I personally recommend the first solution, since that way you don't have to manually show/hide the bar.
