### ISSUE TITLE
hidesBottomBarWhenPushed = true doesn't work 

### ISSUE THREAD

**Issue by alshcompiler** [Minitour/AZTabBarController#38]
Normally you can tell a `viewController` to hide tabbar on push, but it doesn't work using `AZTabBarController`, any advise instead of making : 

`currentTabBar?.setBar(hidden: true, animated: true)`

on `viewDidLoad`, then when click back i show the bar manually ? 

Thanks in advance

**Comment by anirudhamahale** [comment]
Any updates on this feature?
