### ISSUE TITLE
Move to different Index from a ViewController

### ISSUE THREAD

**Issue by mogsten** [Minitour/AZTabBarController#39]
How can I move to a different Index from a ViewController?

If I click on the button on the TabBar, it works fine. But I need to programmatically move to the view controller when a function has finished.
Is this possible?

**Comment by Minitour** [comment]
@mogsten There you go

```swift
self.currentTabBar?.setIndex(2, animated: false)
```

**Comment by mogsten** [comment]
Hello,

How do I get currentTabBar? I am not loading from a ViewController on the tab bar, I am loading from a page that has been pushed from a UINavigationController that was on the TabBar?

**Comment by Minitour** [comment]
`currentTabBar` is an extension variable for UIViewController.
As long as you have an AZTabBarController in the hierarchy you should be fine.
Whatever your `page` is, if it is a sub class of UIViewController you should have access to `currentTabBar`.
