### ISSUE TITLE
Accessing AZTabBar instance

### ISSUE THREAD

**Issue by ElyDantas** [Minitour/AZTabBarController#4]
How to access AZTabBar from another ViewController class ?

I want to hide tabbar when button is clicked in another viewcontroller storyboard/class

**Comment by ElyDantas** [comment]
By making tabController static... dah

public static var tabController:AZTabBarController!

**Comment by Minitour** [comment]
@ElyDantas 
The AZTabBar doesn't include this kinda of feature out of the box, however I can provide a simple solution for you:

Create a custom protocol and specify the events you wish to trigger:
```swift
protocol MyCustomDelegate{
    func requestTabVisability(show: Bool, animate: Bool)
}
```

Then conform your ViewController in which you have an instance member of AZTabBarController to that Custom Delegate:

```swift
extension ViewController: MyCustomDelegate{
    func requestTabVisability(show: Bool, animate: Bool){
             self.tabBar.setBar(hidden: !show, animated: animate)
    }
} 
```

Then in your child view controller, create an instance member of that protocol:
```swift
class MyChildViewController: UIViewController{
       ...
        var delegate: MyCustomDelegate?
       ...
}
```

Now when you are about to add the child view controller to the tab bar simply do this:
```swift
let myChildViewController = MyChildViewController()
myChildViewController.delegate = self //we set the delegate to point to ViewController
tabController.set(viewController: myChildViewController, atIndex: 0)
```

So now every time you wish to hide the tab bar you can do so by doing:
```swift
self.delegate?.requestTabVisability(show: true,animate: true)
```

I hope this helps you solve your problem, if you have any question feel free to ask 😄

**Comment by Minitour** [comment]
@ElyDantas Was your issue resolved?

**Comment by ElyDantas** [comment]
Yes, it worked like a charm !!! Thx, now it is more pattern driven.

**Comment by Minitour** [comment]
Glad to help.
