### ISSUE TITLE
Corner Radius to Selected Button Background

### ISSUE THREAD

**Issue by zaeem-khatib** [Minitour/AZTabBarController#43]
![skype_picture](https://user-images.githubusercontent.com/38113338/45089541-1ee70700-b12a-11e8-989f-b4e385d5a30b.jpeg)

Can we give corner radius to the selected tab bar item background? Similar to the attached screenshot. Any help would be much appreciated.

**Comment by Minitour** [comment]
@zaeem-khatib 

Call this method once on viewDidAppear once your tab bar was loaded.
```swift
func applyCornerRadiusToCenter(){
      let sv: UIStackView? = (tabBar?. buttonsContainer.subviews[0] as? UIStackView)
      if let sv = sv {
           let centerIndex: Int = Int(sv.arrangedSubviews.count / 2) + 1
           let centerView = sv.arrangedSubviews[centerIndex]
           centerView.layer.cornerRadius = 5.0
           centerView.layer.masksToBounds = true
      }
}
```

Note that I have wrote this code blindly without testing so I don't know if it actaully works.

**Comment by zaeem-khatib** [comment]
@Minitour it does work. Thanks a lot for this. Also, could you please tell me if I wanted to add some leading and trailing margins to the stack view, how would that be done? At present it is having no margin from superview.

**Comment by zaeem-khatib** [comment]
@Minitour if you can give a quick solution, it would be much appreciated.

**Comment by Minitour** [comment]
@zaeem-khatib 
There is no way to do that without modifying the source code.

You will need to modify this function:
https://github.com/Minitour/AZTabBarController/blob/master/Sources/AZTabBarController.swift#L1107

in which you can add constants to the constraints that are being added on the top,bottom,left,right.
