### ISSUE TITLE
didSetupInterface vs didSetUpInterface — intentional?

### ISSUE THREAD

**Issue by dsjoerg** [Minitour/AZTabBarController#45]
I was surprised to discover that there are two booleans: didSetupInterface and didSetUpInterface.  Is this intentional that they are both here and have distinct logic?  My urge is to combine them but I don't understand the code well enough yet to be sure how or if this will work.

**Comment by Minitour** [comment]
@dsjoerg 
Yeah this is the result of an unsupervised merge. I guess it went under my radar. Thanks for bringing it to my attention!
