### ISSUE TITLE
Manual installation

### ISSUE THREAD

**Issue by iDevelopper** [Minitour/AZTabBarController#46]
Great project!

What if we don't want to use CocoaPods?

Drag and drop source folder in the project.
Drag and drop EasyNotificationBadge.swift to the project because your project need it.

In AZTabBarController.swift and AZTabBarButton.swift,

import EasyNotificationBage will cause the error: No such module 'EasyNotificationBadge'.

I would suggest adding the build import test in both files:
```
#if canImport(EasyNotificationBadge)
import EasyNotificationBadge
#endif
```
references:
https://github.com/apple/swift-evolution/blob/master/proposals/0075-import-test.md
https://bugs.swift.org/browse/SR-1560

**Comment by Minitour** [comment]
@iDevelopper good idea! Will add it in the next release. Thanks for contributing!
