### ISSUE TITLE
Add a HeaderView for all viewControllers in tabbar

### ISSUE THREAD

**Issue by hcphuc5295** [Minitour/AZTabBarController#47]
Hello, 
I don't know if we can add a headerView which is fixed for all viewControllers in the TabBarVC? Thank you very much.

**Comment by Minitour** [comment]
@hcphuc5295 
By HeaderView you mean Navigation Bar? if so you can. That can be done by having the main view controller which hosts the Tab Bar, wrapped with a UINavigationController.

**Comment by hcphuc5295** [comment]
![image d ios](https://user-images.githubusercontent.com/40792873/45876700-a7f17580-bd9b-11e8-909f-77995c55cdac.png)
Like in this photo, it has a header and I want it to be fixed for all tabs

**Comment by Minitour** [comment]
This is a navigation controller.
In your storyboard select the controller, and then select embed -> embed in a navigation controller.

**Comment by hcphuc5295** [comment]
I will try, thank you @Minitour
