### ISSUE TITLE
Label Color

### ISSUE THREAD

**Issue by SergeyDevUA** [Minitour/AZTabBarController#50]
Hi, how can I change middle tab bar button text color - Indexes?

<img width="223" alt="2018-10-03 17 06 44" src="https://user-images.githubusercontent.com/25286679/46415802-bdb55200-c72e-11e8-8838-aecb5e2d11eb.png">

**Comment by SergeyDevUA** [comment]
Any news please ?

**Comment by Minitour** [comment]
@SergeyDevUA I am working on a fix, see #41.

**Comment by Minitour** [comment]
Fixed with version `1.4.2`.
