### ISSUE TITLE
Custom image for selected state is not working properly

### ISSUE THREAD

**Issue by mubashirhussain** [Minitour/AZTabBarController#51]
I have downloaded the sample code and added my custom image for tab bar, but upon selection the tabbar image is filling the image color instead of rendering the image as it is. See the attached screenshot of simulator and original image how it should render in tab bar.

This is happening because of tab bar selected state color, can you set it to nil so that tabbar can render the selected state image from assets.
![simulator screen shot - iphone 8 - 2018-11-11 at 16 40 47](https://user-images.githubusercontent.com/1871447/48313711-5615e080-e5d1-11e8-970e-c7317eaf4679.png)
![maps_tab_s 3x](https://user-images.githubusercontent.com/1871447/48313716-67f78380-e5d1-11e8-9034-1e7fd3127231.png)

**Comment by Minitour** [comment]
Hi, see issue #13

**Comment by mubashirhussain** [comment]
Thanks
