### ISSUE TITLE
Value of type 'AZTabBarController' has no member 'pushViewController'

### ISSUE THREAD

**Issue by Sinisimbu** [Minitour/AZTabBarController#52]
I want to push view controller from tab 0. I am using this code "self.currentTabBar?.pushViewController(secondViewController, animated: true)". But i cant do this because this error happened

**Comment by Minitour** [comment]
try 
```swift
self.navigationController?.pushViewController(secondViewController, animated: true)
```

This should work given that:
- `self` is the controller embedded in the tab bar.
- The tab bar is embedded in a controller that has a navigation controller.

UINavigationController
|
| ---  Primary View Controller
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;| --- Tab Bar Controller
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;| Custom View Controller (tab 0)
