### ISSUE TITLE
Crash with normal use

### ISSUE THREAD

**Issue by SteynMarnus** [Minitour/AZTabBarController#53]
Hi there,

I followed the usage tutorial on the ReadMe exactly and my app seems to crash, here is the exception:
![screenshot 2018-12-10 at 15 50 11](https://user-images.githubusercontent.com/19153368/49736789-bca32280-fc93-11e8-9f98-e13b68269729.png)

And here is how I use the AZTbarBar:

        var icons = [String]()
        icons.append("document")
        icons.append("group")
        icons.append("compass")
        icons.append("cogwheel")

        var selectedIcons = [String]()
        selectedIcons.append("document_selected")
        selectedIcons.append("group_selected")
        selectedIcons.append("compass_selected")
        selectedIcons.append("cogwheel_selected")
        
        tabController = AZTabBarController.insert(into: self, withTabIconNames: icons, andSelectedIconNames: selectedIcons)
        
        let documentsPage = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "documentsViewController")
        let groupPage = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "groupViewController")
        let findPage = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "findViewController")
        let settingsPage = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "settingsViewController")
        
        tabController.setViewController(documentsPage, atIndex: 0)
        tabController.setViewController(groupPage, atIndex: 1)
        tabController.setViewController(findPage, atIndex: 2)
        tabController.setViewController(settingsPage, atIndex: 3)

It seems crash when the **AZTabBarController.insert()** line is hit

**Comment by SteynMarnus** [comment]
> @SteynMarnus I guess this bug went unnoticed. try setting the `selectedColor` property before setting a view controller:
> 
> ```swift
> //the color of the icon when a menu is selected
> tabController.selectedColor = .orange 
> ```

I see, however it crashes before even setting the view controllers - the line that construct the bar `AZTabBarController.insert()` is throwing the exception. Is there a way to create the bar with the init method or so? Thank you for attending to this issue 👍

**Comment by SteynMarnus** [comment]
> @SteynMarnus I guess this bug went unnoticed. try setting the `selectedColor` property before setting a view controller:
> 
> ```swift
> //the color of the icon when a menu is selected
> tabController.selectedColor = .orange 
> ```

That seems to patch it for now. Thank you for getting on this issue 👍

**Comment by Minitour** [comment]
Do you mind attaching your entire swift file?

**Comment by SteynMarnus** [comment]
[ViewController.swift.zip](https://github.com/Minitour/AZTabBarController/files/2667029/ViewController.swift.zip)
Here is my swift files are requested
