### ISSUE TITLE
setTitle doesn't work

### ISSUE THREAD

**Issue by gerchicov-bp** [Minitour/AZTabBarController#54]
copied your example code from readme. The tab bar is shown with icons, titles are missing.
Maybe is this because of big icon size?

**Comment by Minitour** [comment]
@gerchicov-bp 
I recommend you use icons with 24px size such that x2 and x3 will still fit.

However if the icon size is not the issue try going through the example provided and see if you missing anything:
https://github.com/Minitour/AZTabBarController/blob/master/AZTabBarController/ViewController.swift
