### ISSUE TITLE
View Controller that is presented has controls blocked

### ISSUE THREAD

**Issue by iJasonWade** [Minitour/AZTabBarController#57]
When I try to present a new view controller the AZTabBarController view hierarchy is always in the front and blocks the controls that are in the presented ViewController from being pressed. I have tried presenting from all of the controllers in the heirarchy and tried to manually bring the presented view controllers view to the front.

**Comment by Minitour** [comment]
@iJasonWade have you tried accessing the parent controller of the tab bar and presenting from it?
```
self.currentTabBar?.present(...)
```
