### ISSUE TITLE
Multiple issues

### ISSUE THREAD

**Issue by and0m** [Minitour/AZTabBarController#58]
Initially, I thought the problem is within my app, but then I tried the example, which has the same issue. Basically, when a user clicks multiple times on the buttons it seems that sometimes the toggle fails. Sometimes the app switches to a completely different view (usually the home).

A way to replicate the behavior would be to click on the "feed" tab, from the example project, in multiple succession (almost like rage clicking it).

I assume this is due to the views being stacked on top of each other. I don't really know what's going on.

Another issue that I'm facing is that the AZTabController seems to be on top of everything in my view and screws up element interaction. There is another issue related to this bug but the suggestion didn't solve my problem. Seems like the TabController is messing up the NavigationController.

Better documentation will be really helpful...

**Comment by iDevelopper** [comment]
I think your last point this is relative to the additional safe area inset that is missing, because this class is not a UITabBarController subclass and the framework does not provide anything for additional safe area inset...

**Comment by and0m** [comment]
> safe area inset

Thanks for the heads up. Indeed, one of my views didn't have a proper safe area setup. That fixed the problem.

**Comment by iDevelopper** [comment]
Great!

**Comment by Minitour** [comment]
@and0m 
> Initially, I thought the problem is within my app, but then I tried the example, which has the same issue. Basically, when a user clicks multiple times on the buttons it seems that sometimes the toggle fails. Sometimes the app switches to a completely different view (usually the home).
> 
> A way to replicate the behavior would be to click on the "feed" tab, from the example project, in multiple succession (almost like rage clicking it).
> 
> I assume this is due to the views being stacked on top of each other. I don't really know what's going on.

I could not reproduce this behaviour. Can you tell me which device were you using? was it simulator or a real device, and if it was a real device then what was it's model as well as which iOS version did you run it on.
