### ISSUE TITLE
Selector on top for iPhone X

### ISSUE THREAD

**Issue by davidebettio** [Minitour/AZTabBarController#59]
Is there a way to put selector on the top of the tabbar instead of the bottom?

In a old version of this lib I forked the repo and use this code in the file `AZTabBarController.swift`:

a property:

```
/// The position of the selection indicator.
open var selectionIndicatorOnBottom:Bool = true{
    didSet{
        updateInterfaceIfNeeded()
     }
}
```
and this code at the bottom of `setupSelectionIndicatorConstraints()`
```
if (selectionIndicatorOnBottom) {
    selectionIndicator.bottomAnchor.constraint(equalTo: buttonsStackView.bottomAnchor).isActive = true
} else {
    selectionIndicator.topAnchor.constraint(equalTo: buttonsStackView.topAnchor).isActive = true
}
```
and it worked, but in the latest version it doesn't work

**Comment by Minitour** [comment]
@davidebettio I need to look into it. I recommend however to instead of making it appear on top, have it as it, set it’s background color to clear and add a subview to it which looks in the way you want it to be. See issue #11.
