### ISSUE TITLE
How to change the selected TabBarItem background color

### ISSUE THREAD

**Issue by StackHelp** [Minitour/AZTabBarController#62]
I'm trying to change the background of a selected TabBarItem like below
<img width="428" alt="InyGc" src="https://user-images.githubusercontent.com/41230403/77225694-72e40000-6b97-11ea-85ef-86ea5638f4d7.png">

how can we achieve this?

**Comment by Minitour** [comment]
Have you tried 
```
tabBarController.highlightedBackgroundColor = myColor

tabController.highlightButton(atIndex: 2) 
```

**Comment by StackHelp** [comment]
@Minitour let me check

**Comment by Minitour** [comment]
I’m not sure I understand your desired functionality. Do you want the background to change when you click a button? Or just have a fixed background for one button like you showed in the picture?

**Comment by StackHelp** [comment]
Yes, Want to change the background color on click of tab item.

**Comment by Minitour** [comment]
Yeah I don’t remember implementing such functionality, your delegate workaround would do just fine.
