### ISSUE TITLE
Weird Issue: Just one image does not set

### ISSUE THREAD

**Issue by StackHelp** [Minitour/AZTabBarController#65]
I am trying to set different images in `TabBar` but just one image from them doesn't work.

        var icons = [UIImage]()
        icons.append(UIImage(named: "ic_tab_wallpaper")!)
        icons.append(UIImage(named: "ic_tab_maps")!)
        icons.append(UIImage(named: "ic_tab_wallpaper")!)
        icons.append(UIImage(named: "ic_tab_shop")!)
        icons.append(UIImage(named: "ic_tab_profile")!)
        
        var sIcons = [UIImage]()
        sIcons.append(UIImage(named: "ic_tab_wallpaper_selected")!)
        sIcons.append(UIImage(named: "ic_tab_maps")!)
        sIcons.append(UIImage(named: "ic_tab_wallpaper_selected")!)
        sIcons.append(UIImage(named: "ic_tab_shop_selected")!)
        sIcons.append(UIImage(named: "ic_tab_profile_selected")!)

Every other image except `ic_tab_maps` works and shows in `TabBar`. I have tried to check in your example as well but it doesn't work. 

![Screenshot 2020-04-30 at 1 40 59 PM](https://user-images.githubusercontent.com/41230403/80687672-46050000-8ae8-11ea-975b-fb835efb7aca.png)

Here is the image If you like to look at it.
![MAPS@3x](https://user-images.githubusercontent.com/41230403/80687502-063e1880-8ae8-11ea-8f0f-0edf3eb3b340.png)

**Comment by Minitour** [comment]
Are your images placed in the XCAssets catalog?

**Comment by StackHelp** [comment]
@Minitour Yes. Edited a question. Please check the tabbar

**Comment by Minitour** [comment]
Oh it’s the second one... yeah this is because it automatically sets the image to have a tint color and because your image doesn’t have an alpha it colors all of it.

To fix this you have two options:
- set ignoreIconColors to true.
- get an image with an alpha component.

**Comment by StackHelp** [comment]
@Minitour the image is with alpha 100%. I don't understand the second option

**Comment by Minitour** [comment]
I’ll rephrase. You are correct the image has an alpha component, but the part of it which you wish to view is not transparent.

Either get rid of the rectangle surrounding the map pin, or get a rectangle with map in cut out of it.
